syntax = "proto3";
package project;

import "google/protobuf/empty.proto";

service ProjectApi {
  rpc GetAll(google.protobuf.Empty) returns (Projects);
  rpc Create(CreateReq) returns (google.protobuf.Empty);
  rpc Delete(DeleteReq) returns (google.protobuf.Empty);
}

message Project {
  int32 Id = 1;
  string Name = 2;
  string Description = 3;
}

message Projects {
  repeated Project Projects = 1;
}

message CreateReq {
  string Name = 1;
  string Description = 2;
}

message DeleteReq {
  string Name = 1;
}
