services:
  envoy:
    image: dionisius77/dply-envoy:v1.0
    container_name: dply-envoy
    networks:
      - vpn-net

  dply-react:
    image: dionisius77/dply-react:v1.0
    container_name: dply-react
    environment:
      - REACT_APP_GRPC_WEB_HOST=http://envoy.tcl.internal
    depends_on:
      - envoy
    networks:
      - vpn-net

networks:
  vpn-net:
    external: true
